### ISSUE TITLE
RolePlay

### ISSUE THREAD

**Issue by mxneyy** [space2pacman-misc/mafia2-online-roleplay-server#1]
Hi! I'm very interested of your roleplay mafia 2 server and i wan't to ask if you working on it and when you will have it done? I have friend mafia 2 youtuber and we wan't to create mafia online community, but we need a good roleplay. You can contact me on discord Lil_Resty#9311

**Comment by space2pacman** [comment]
I made only one script (work on the docks at Derek) and I do not plan to do more yet.
